html forms- Hannah Hoang
hannahhoanggg/c0723-code-solutions pull request #21
Opened 2023-07-18 23:03 UTC by hannahhoanggg

![Screenshot 2023-07-18 122141](https://github.com/hannahhoanggg/c0723-code-solutions/assets/136301731/2593318d-fffc-4eaf-aa82-4937330486c5)

2023-07-19 17:22 UTC, shawnkost requested changes
Some changes here Hannah!

2023-07-19 17:22 UTC, shawnkost commented on html-forms/index.html
> +          <select id="why-is-coding-cool-select">
This should be `id="coding-select"` to match your `for` attribute of the `label`

2023-07-19 17:22 UTC, shawnkost commented on html-forms/index.html
> +          <label for="favorite-language">Favorite Language (choose one)</label>
This should just be a `p` tag, because it's not linked to any `input`

2023-07-19 17:22 UTC, shawnkost commented on html-forms/index.html
> +            <label for="JavaScript">JavaScript</label>
`id`s should always be lowercase

2023-07-19 17:22 UTC, shawnkost commented on html-forms/index.html
> +            >
This should just be a `p` since it's not associated with any `input`

2023-07-19 17:22 UTC, shawnkost commented on html-forms/index.html
> +          <textarea cols="30" rows="10"></textarea>
Needs an `id="comments"`

2023-07-19 21:38 UTC, hannahhoanggg commented on html-forms/index.html
> +          <textarea cols="30" rows="10"></textarea>
got it!

2023-07-20 16:42 UTC, shawnkost requested changes
One change here Hannah!

2023-07-20 16:42 UTC, shawnkost commented on html-forms/index.html
> +            <label for="comments" id="comments">Comments</label>
Wrong place. The `id="comments"` needs to go on the `textarea`. The `for` attribute of the `label` matches the `id` of an `input`, `textarea`, etc.

2023-07-21 20:58 UTC, shawnkost approved these changes
👍🏻

2023-07-21 21:48 UTC, merged